import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font Propo"

[window]
decorations = "none"
opacity = 0.95

[window.padding]
x = 4
y = 3
