"alacritty.toml" = "../.config/alacritty/alacritty.toml"
"alias.zsh" = "../.oh-my-zsh/custom/alias.zsh"
"starship.toml" = "../.config/starship.toml"
bat = "/Users/rafaelvillegasmichel/.config/bat"
"path.zsh" = "../.oh-my-zsh/custom/path.zsh"
yabai = "../.config/yabai"
skhd = "../.config/skhd"
"tmux.conf" = "../.config/tmux/tmux.conf"
