"alias.zsh" = "../.oh-my-zsh/custom/alias.zsh"
"path.zsh" = "../.oh-my-zsh/custom/path.zsh"
"starship.toml" = "../.config/starship.toml"
bat = "../.config/bat"
skhd = "../.config/skhd"
"config.yml" = "../Library/Application Support/lazygit/config.yml"
yabai = "../.config/yabai"
"tmux.conf" = "../.config/tmux/tmux.conf"
"alacritty.toml" = "~/.config/alacritty/alacritty.toml"
nvim = "../.config/nvim"
