yabai = "../.config/yabai"
skhd = "../.config/skhd"
bat = "../.config/bat"
"com.mitchellh.ghostty" = "~/Library/Application Support/com.mitchellh.ghostty"
"path.zsh" = "../.oh-my-zsh/custom/path.zsh"
"config.yml" = "../Library/Application Support/lazygit/config.yml"
nvim = "~/.config/nvim"
"alias.zsh" = "../.oh-my-zsh/custom/alias.zsh"
"tmux.conf" = "../.config/tmux/tmux.conf"
"alacritty.toml" = "~/.config/alacritty/alacritty.toml"
"starship.toml" = "../.config/starship.toml"
