nvim = "../.config/nvim"
yabai = "../.config/yabai"
skhd = "../.config/skhd"
"path.zsh" = "../.oh-my-zsh/custom/path.zsh"
"starship.toml" = "../.config/starship.toml"
"alias.zsh" = "../.oh-my-zsh/custom/alias.zsh"
"tmux.conf" = "../.config/tmux/tmux.conf"
"config.yml" = "../Library/Application Support/lazygit/config.yml"
bat = "../.config/bat"
"alacritty.toml" = "../.config/alacritty/alacritty.toml"
